import { NextResponse } from 'next/server'
import { createServerClient } from '@/lib/supabase/server'
import type { CreateCheckInRequest, CreateCheckInResponse } from '@/lib/check-in/types'

export const dynamic = 'force-dynamic'

/**
 * POST /api/check-in/create
 * Create a new check-in record with a unique token
 * Called when a new booking is created
 */
export async function POST(request: Request) {
  try {
    const body = await request.json() as CreateCheckInRequest
    
    const {
      bookingId,
      guestName,
      guestPhone,
      guestEmail,
      checkInDate,
      checkOutDate,
      numAdult = 2,
      numChild = 0,
      userId,
    } = body

    // Validate required fields
    if (!bookingId || !guestName || !guestPhone || !checkInDate || !checkOutDate || !userId) {
      return NextResponse.json(
        { success: false, error: 'Missing required fields' } as CreateCheckInResponse,
        { status: 400 }
      )
    }

    const supabase = createServerClient()

    // Generate a unique token (UUID will be generated by database)
    const { data: checkIn, error } = await supabase
      .from('check_ins')
      .insert({
        booking_id: bookingId,
        user_id: userId,
        token: crypto.randomUUID(), // Generate unique token
        guest_name: guestName,
        guest_phone: guestPhone,
        guest_email: guestEmail || null,
        check_in_date: checkInDate,
        check_out_date: checkOutDate,
        num_adults: numAdult,
        num_children: numChild,
        status: 'pending',
      })
      .select()
      .single()

    if (error) {
      console.error('❌ Error creating check-in:', error)
      return NextResponse.json(
        { success: false, error: 'Failed to create check-in record' } as CreateCheckInResponse,
        { status: 500 }
      )
    }

    // Get the base URL
    const baseUrl = process.env.NEXTAUTH_URL || 
                    (request.headers.get('host') ? `https://${request.headers.get('host')}` : 'http://localhost:3000')
    
    const checkInLink = `${baseUrl}/check-in/${checkIn.token}`

    console.log('✅ Check-in created:', {
      id: checkIn.id,
      token: checkIn.token,
      guest: guestName,
      link: checkInLink
    })

    return NextResponse.json({
      success: true,
      checkInId: checkIn.id,
      token: checkIn.token,
      link: checkInLink,
    } as CreateCheckInResponse)

  } catch (error) {
    console.error('❌ Unexpected error creating check-in:', error)
    return NextResponse.json(
      { success: false, error: 'Internal server error' } as CreateCheckInResponse,
      { status: 500 }
    )
  }
}
